### ISSUE TITLE
Issue with downloading now

### ISSUE THREAD

**Issue by ModernAesthetics** [spicycoder/TutorialsDownloader#10]
This no longer seems to work or it does not work if the course had started to download and you try and redownload

**Comment by spicycoder** [comment]
I find the app is still working. When you are already downloading a course, stopped it for some reason, you can continue downloading same course by providing the same URL again. If it is still not working, try the following

1. Make sure you click the update button on App Start & wait for update to finish.
1. Look into the folders & if you find any file with extension .temp, delete it & try again
1. Make sure the credentials you are using is valid & active
