### ISSUE TITLE
Your projeto does not work

### ISSUE THREAD

**Issue by DaviBittencourt** [spicycoder/TutorialsDownloader#4]
It seems to me that pluralsight has modified its folders and site layout of courses. What changes are needed?

**Comment by spicycoder** [comment]
Hi Davi,
Thanks for your interest in the project.
I have made necessary changes in my recent commit.
Please try and let me know how it goes.

Also make sure to click the Update button in the Login dialog atleast once a day.

Thanks

**Comment by DaviBittencourt** [comment]
It worked very well, thanks for the update and attention !!

**Comment by DaviBittencourt** [comment]
Hello, I discovered a problem downloading videos that have the special character "%", I do not know if the problem happens with other characters, but with that the video not download.

MainWindow.xaml.cs Line 144 ==> (video.Name)

**Comment by spicycoder** [comment]
Hi,
I think I fixed it sometime back.
If you look at Line 333, I've replaced % with %% to fix this issue.
But surprised to know it still exists. let me check & get back.

**Comment by spicycoder** [comment]
If you don't mind, can you please share a course name, that contains video with %?

**Comment by DaviBittencourt** [comment]
https://app.pluralsight.com/library/courses/pragmatic-unit-testing/table-of-contents
-> Introduction
---->100% Coverage
