### ISSUE TITLE
Edit the wait time

### ISSUE THREAD

**Issue by hong1999** [spicycoder/TutorialsDownloader#7]
May I know how to change the "wait time avoid throttling"
5 second seem too fast, will get pluralsight blocked ip

**Comment by spicycoder** [comment]
Hi,
The wait time is not 5 seconds
The wait time varies, based on the video length.

Say if the video is 1 minute 28 seconds long, it'll wait for 1 minute 28 seconds + 5 seconds before continuing with next clip download
Hope this answers your question.
