### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by raphaeltb2** [spicycoder/TutorialsDownloader#8]
Sorry for the noob question, where i find a tutorial teaching how this work

**Comment by spicycoder** [comment]
At this point, we don't have a **How To** page, yet.
But it's simple 3 step process, as seen in
https://spicycoder.github.io/TutorialsDownloader/

1. Enter your pluralsight credentials, and a directory where you want to download the videos & click on **Save** button
2. Copy paste the URI of the course you want to download. The URI should end with **table-of-contents**.
3. You can see the video being downloaded in the directory you specified earlier.

I would recommend you to click on **Update** button, once a day, before beginning any downloads.
